### ISSUE TITLE
Issue using ->includeOnly()

### ISSUE THREAD

**Issue by echomedia-alan** [coderatio/simple-backup#2]
Hi, I am trying to run the new v1.0.1 feature to include a specific table only ( eg. ->includeOnly(['carts', 'houses', 'categories']) ) but am getting this error repeatedly: Fatal error: Uncaught Error: Using $this when not in object context in \vendor\coderatio\simple-backup\src\SimpleBackup.php:442

The same appears to be the case with excludeOnly() also

Any suggestions would be appreciated

**Comment by coderatio** [comment]
@echomedia-alan we have worked on this will be shipping it tomorrow.
