### ISSUE TITLE
Codeigniter 4 Support?

### ISSUE THREAD

**Issue by brevv99** [coderatio/simple-backup#6]
Hello, whether this library has support for Codeigniter version 4 and PHP version 8? I wanna to integrate this library to my project.

**Comment by ChibuezeAgwuDennis** [comment]
> Hello, whether this library has support for Codeigniter version 4 and PHP version 8? I wanna to integrate this library to my project.

Hello contact  me I will make the library to be compatible with Codeigniter 4 and php 8
