### ISSUE TITLE
Is it still mantained?

### ISSUE THREAD

**Issue by vince844** [coderatio/simple-backup#7]
Hi,
Is this library still mantained? Is it save to use in production?

**Comment by chriscolombos** [comment]
Hello vince844,
I am using it for a Backup Feature on my project and it works fine.
But kindly note that it has an issue which I added. If you solve it, then the backup file generated will be executable with no MySQL syntax errors.

**Comment by coderatio** [comment]
Somehow maintained. Yes, you can use this library on production for sure @vince844
